s_ip = "192.168.1.20"
modbus_add_signal(s_ip, 255, 0, 2, "RI_WSG_STATE")
modbus_set_signal_update_frequency("RI_WSG_STATE", 50)
modbus_add_signal(s_ip, 255, 0, 3, "RO_WSG_CMDFLAGS")
modbus_set_signal_update_frequency("RO_WSG_CMDFLAGS", 50)
modbus_add_signal(s_ip, 255, 1, 3, "RO_WSG_WIDTH")
modbus_set_signal_update_frequency("RO_WSG_WIDTH", 50)
modbus_add_signal(s_ip, 255, 2, 3, "RO_WSG_SPEED")
modbus_set_signal_update_frequency("RO_WSG_SPEED", 50)
modbus_add_signal(s_ip, 255, 3, 3, "RO_WSG_FORCELIM")
modbus_set_signal_update_frequency("RO_WSG_FORCELIM", 125)
modbus_set_runstate_dependent_choice("RO_WSG_CMDFLAGS",0)
modbus_set_runstate_dependent_choice("RO_WSG_WIDTH",0)
modbus_set_runstate_dependent_choice("RO_WSG_SPEED",0)
modbus_set_runstate_dependent_choice("RO_WSG_FORCELIM",0)
global i_WSG_Pos=1000
global i_WSG_Speed=5000
global i_WSG_Force=5000
global s_WSG_State = "Idle"
